export enum ActionType {
GET_PERSONAL_ACCOUNTS = 'GET_PERSONAL_ACCOUNTS',
GET_PERSONAL_BALANCES = 'GET_PERSONAL_BALANCES',
PERSONAL_ACCOUNTS_ERROR = 'PERSONAL_PAYMENTS_ERROR',
PERSONAL_BALANCES_ERROR = 'PERSONAL_BALANCES_ERROR',
SET_ACCOUNTS_SCREEN_ERROR = 'SET_ACCOUNTS_SCREEN_ERROR',
SET_ACCOUNTS_SCREEN = 'SET_ACCOUNTS_SCREEN',
CLEAR_ACCOUNTS_SCREEN = 'CLEAR_ACCOUNTS_SCREEN',
GET_CORPORATE_BALANCES = 'GET_CORPORATE_ACCOUNTS',
CORPORATE_BALANCES_ERROR = 'CORPORATE_ACCOUNTS_ERROR',
GET_CORPORATE_ACCOUNTS = 'GET_CORPORATE_ACCOUNTS',
CORPORATE_ACCOUNTS_ERROR = 'CORPORATE_ACCOUNTS_ERROR'
}



